# TODO: Remover ?
version: '3'

services:
  reactjs:
    container_name: platiagro-web-ui-reactjs
    image: node:lts
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - ${PORT:-80}:${PORT:-80}
    environment:
      - PORT=${PORT:-80}
    tty: true
    stdin_open: true
